[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '')]
param(
    [string] $Project = '.\src\CSharp\Kestrun\Kestrun.csproj',
    [string] $Path = 'THIRD-PARTY-NOTICES.md',
    [parameter(Mandatory = $true)]
    [string] $Version
)
Write-Host "Generating third-party notices..."
$nugetLicenses = nuget-license -i $Project -o markdown |
Where-Object { $_ -notmatch '^\|\s+\|' } |  # drop lines like "|    |..." with only whitespace between pipes
ForEach-Object {
    if ($_ -match '^\|') {
        $cols = $_ -split '\|'
        if ($cols.Length -ge 4) {
            # remove the two trailing "Error" / "Error Context" columns (they're before the final empty slot)
            ($cols[0..($cols.Length - 4)] + $cols[-1]) -join '|'
        }
        else {
            $_
        }
    }
    else {
        $_
    }
}
# Compose a soft, compliant introduction


$start = 2025
$now = (Get-Date).Year
$years = if ($start -eq $now) { $now } else { "$start–$now" }

$kestrunHeader = @"
<!--
  AUTO-GENERATED FILE — DO NOT EDIT.

  Project: Kestrun
  License: MIT
  Generated by: invoke-build ThirdPartyNotices
  Generated on: $((Get-Date).ToUniversalTime().ToString("o"))
  Commit: $(git rev-parse --short HEAD)
  Version: $Version

  To regenerate, run: .\Kestrun.build.ps1
  Do not modify manually; changes will be overwritten.
-->

# Kestrun - Third-Party Notices

**License:** [MIT](https://licenses.nuget.org/MIT) (SPDX: MIT)
**Copyright © $years** Kestrun Contributors

Kestrun is distributed under the MIT License.
This document lists third-party software components used by Kestrun, along with their licenses.

---

"@
[System.Text.StringBuilder]$sb = [System.Text.StringBuilder]::new()
# Add a note about the generation of this file
foreach ($line in $nugetLicenses ) {

    $null = $sb.Append( ($line -replace 'ΓÇô', '-' -replace '┬⌐', '© '
            #-replace 'https://licenses.nuget.org/MIT', '[MIT](https://licenses.nuget.org/MIT)' `
            #-replace 'https://licenses.nuget.org/Apache-2.0', '[Apache-2.0](https://opensource.org/license/apache-2-0/)')
        )
    )
    $null = $sb.AppendLine()
}

# Combine everything
$kestrunHeader + "`n" + ($sb.ToString()) | Set-Content -Path $Path -Encoding UTF8

Write-Host "Third-party notices generated at: $Path" -ForegroundColor Green
Write-Host "Please review the generated file for compliance with third-party licenses."